# See https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System
sudo: required

# Choose a lightweight base image; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - "$HOME/.stack"

# GHC depends on GMP. You can add other dependencies here as well.
addons:
  apt:
    packages:
    - libgmp-dev

# The different configurations we want to test. You could also do things like
# change flags or use --stack-yaml to point to a different file.
# See list here -- https://www.stackage.org/snapshots
env:
#- $RESOLVER="lts-0.7"    # Fails on Travis (unsupported GHC on Travis)
#- $RESOLVER="lts-2.22"   # Fails on Travis (too old)
# - $RESOLVER="lts-3.22"  # Fails on Travis (too old)
- $RESOLVER="lts-6.35"
- $RESOLVER="lts-7.24"
#- $RESOLVER="lts-8.0"    # Removed from most recents on Stackage; Unreliable/slow build on Travis
- $RESOLVER="lts-9.21"
- $RESOLVER="lts-9.6"     # 'Haskell for Mac' LTS
- $RESOLVER="lts-10.3"
- $RESOLVER="lts-11.22"
- $RESOLVER="lts-12.7"
- $RESOLVER="nightly"

before_install:
# Download and unpack the stack executable -- https://docs.haskellstack.org/en/stable/travis_ci/?highlight=travis
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
# Build dependencies
- stack --resolver $RESOLVER --no-terminal --install-ghc test --only-dependencies

script:
# Build the package, its tests, and its docs and run the tests
- stack --resolver $RESOLVER --no-terminal --install-ghc test --haddock --no-haddock-deps
# List components explicitly; ignoring failure
- stack --resolver $RESOLVER exec ghc-pkg list || true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/33a1859c14283f0dbab6
    on_success: change
    on_failure: always
    on_start: never

## Deploy (tagged commits) to Hackage; generated by travis CLI
#before_deploy: "echo '=== BEGIN deployment ==='"
#deploy:
#  provider: hackage
#  username: Orome
#  password:
#    secure: lJTICRAD8m+NePYSnyol1TU1zAyuv9YUmR1mfqE5qTrJnauERarmMEVJXglQUASyAT+JfLSoRqJfQWcixE1YTmcXrijIxZicX7G/t6FqPrJDiz+7lpCg4sXBa4ZAbahwvprkBB1eJUN+/9MUjEeX8a+N/lT/hTvnoAFiM2SW1tfS9YuYTeKYCBNMgh6Li8X4cwvI0nsyWyDj7Q+2n1rti6yBSSt2NdXpxVUGzmn4TiDjbX6B3VNZSlwhMb7h9nw11Yf6UkbjI5r4G8eUAJ5o+YOpVGK41+2IXITrO6YnR7Ma3EmMiOADuG1KkJEUrc9juWy6RmjFO+Zs2YIHiYPKoLZXR1w1pRuSlre3vLJwMKj3nFF2aAgawzjqGpmtJlJLn1D+uIrMnUo5lNb4VNHDNTnlmnQAESZmK/lhhqOp/2CebVp0e2p2bjnJUHKVb3ptXmzek9ppS6T9fBhu9/am/4N3Yi1EUurlxVl0xE1eL/3zQX7vVwPrrjk6kDHgVqrlRDZWvf4/MBgyRUitE12w1oRr04cgcivtv2ipov30EdQoUpMy3ABq8EMITAFXTeNPWtEL+3XUqp9SQfxxnycK1Zm/xAsNgIDQl27xY+XYgF585A+cAkhjXkOhS2h7vDw7z2CXDpXcw46IcyoXiPI+9doLX9rTJF8rzJLVksGbPrE=
#  on:
#    repo: orome/crypto-enigma-hs
#    branch: hackage
#    tags: true
#after_deploy: "echo '=== END deployment ==='"
