name: Licence Scan

on:
  push:
    branches: [develop, hackage]

jobs:
  fossa-scan:
    name: FOSSA Licence Scan
    runs-on: ubuntu-latest
    steps:

      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup Haskell
        uses: haskell/actions/setup@v1
#        with:
#          enable-stack: true

      - name: Scan licences
        uses: fossas/fossa-action@v1
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}

